### PR TITLE
WIP: go modules switch & go version update

### PR DESCRIPTION
**Pull request by ghouscht**
I would like to help moving to go modules and building kube-router with a recent go version. Currently a work in progress.

Related issues:
#834 
#802
#784

### CODE REVIEW

**Comment by ghouscht** [comment]
Had no time to work on this during the last days and now travis seems to be somehow broken...

There is still an issue with a test, which seems to run into the configured test timeout of 30s. Will try to look into this in the upcoming week (any help apreciated 😄).

**Comment by murali-reddy** [comment]
thanks @ghouscht for your effort.

If you are stuck with anything (CI, unit tests etc) please share, happy to help

**Comment by ghouscht** [comment]
Here is the stack trace from the test which timeouts. I started the test with `go test -mod=vendor -v -timeout 30s github.com/cloudnativelabs/kube-router/pkg/..`:
```
=== RUN   Test_advertiseClusterIPs/add_bgp_path_for_service_with_ClusterIP
panic: test timed out after 30s

goroutine 74 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001b5100, 0x1982f53, 0x18, 0x19ff460, 0x48cb01)
	/usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0001b4200)
	/usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0001b4200, 0xc00043bdc0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0003eeae0, 0x28a7940, 0xa, 0xa, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0004b1980, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:62 +0x135

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x28b62e0)
	/home/thomas/go/kube-router/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/home/thomas/go/kube-router/vendor/github.com/golang/glog/glog.go:410 +0x26f

goroutine 8 [syscall]:
os/signal.signal_recv(0x4611d6)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 43 [chan receive]:
testing.(*T).Run(0xc0001b5200, 0x199bae8, 0x27, 0xc0003d9880, 0xc0001cd988)
	/usr/local/go/src/testing/testing.go:961 +0x377
github.com/cloudnativelabs/kube-router/pkg/controllers/routing.Test_advertiseClusterIPs(0xc0001b5100)
	/home/thomas/go/kube-router/pkg/controllers/routing/network_routes_controller_test.go:161 +0x9e0
testing.tRunner(0xc0001b5100, 0x19ff460)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350

goroutine 44 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).mgmtOperation.func1(0xc00041c060, 0xc00030be28)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:176 +0x3d
github.com/osrg/gobgp/server.(*BgpServer).mgmtOperation(0xc000031b00, 0xc0004aa0b0, 0x1a00901, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:182 +0xed
github.com/osrg/gobgp/server.(*BgpServer).Stop(0xc000031b00, 0x1, 0xc000215af0)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:1750 +0x65
github.com/cloudnativelabs/kube-router/pkg/controllers/routing.Test_advertiseClusterIPs.func1(0xc0001b5200)
	/home/thomas/go/kube-router/pkg/controllers/routing/network_routes_controller_test.go:205 +0x60b
testing.tRunner(0xc0001b5200, 0xc0003d9880)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350

goroutine 45 [semacquire]:
internal/poll.runtime_Semacquire(0xc0003a1b28)
	/usr/local/go/src/runtime/sema.go:61 +0x42
internal/poll.(*FD).Close(0xc0003a1b00, 0xc0003a1b00, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:109 +0x8f
net.(*netFD).Close(0xc0003a1b00, 0xc0001340e0, 0x203000)
	/usr/local/go/src/net/fd_unix.go:184 +0x4f
net.(*TCPListener).close(...)
	/usr/local/go/src/net/tcpsock_posix.go:156
net.(*TCPListener).Close(0xc0004318c0, 0xc000309770, 0x407145)
	/usr/local/go/src/net/tcpsock.go:274 +0x4a
github.com/osrg/gobgp/server.(*TCPListener).Close(0xc0003d98f0, 0xc0003f19b0, 0xc000309818)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:41 +0x43
github.com/osrg/gobgp/server.(*BgpServer).Stop.func1(0xc0002aa438, 0xc000309f00)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:1758 +0x15f
github.com/osrg/gobgp/server.(*BgpServer).handleMGMTOp(0xc000031b00, 0xc0003a4d80)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:171 +0x47
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc000031b00)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:305 +0x4ae
created by github.com/cloudnativelabs/kube-router/pkg/controllers/routing.Test_advertiseClusterIPs.func1
	/home/thomas/go/kube-router/pkg/controllers/routing/network_routes_controller_test.go:162 +0x66

goroutine 46 [select]:
github.com/eapache/channels.(*InfiniteChannel).infiniteBuffer(0xc000431880)
	/home/thomas/go/kube-router/vendor/github.com/eapache/channels/infinite_channel.go:49 +0x133
created by github.com/eapache/channels.NewInfiniteChannel
	/home/thomas/go/kube-router/vendor/github.com/eapache/channels/infinite_channel.go:19 +0x158

goroutine 47 [syscall]:
syscall.Syscall6(0x120, 0x5, 0xc000513b08, 0xc000513aec, 0x80800, 0x0, 0x0, 0x203030203020302, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.accept4(0x5, 0xc000513b08, 0xc000513aec, 0x80800, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1484 +0x7b
syscall.Accept4(0x5, 0x80800, 0x1000, 0xc0003aab40, 0x20300000000000, 0x7f7a8f11afff, 0x1000)
	/usr/local/go/src/syscall/syscall_linux.go:541 +0x88
internal/poll.accept(0x5, 0x72, 0x20300000000000, 0x0, 0x0, 0x8000040000000000, 0x0, 0xc0001b0ca0)
	/usr/local/go/src/internal/poll/sock_cloexec.go:17 +0x3f
internal/poll.(*FD).Accept(0xc0003a1b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:377 +0x113
net.(*netFD).accept(0xc0003a1b00, 0xc0001b0de0, 0xc0001b0e88, 0x8000)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0004318c0, 0xc0000c90e0, 0xc0001b0fc8, 0x12e68d8)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0004318c0, 0x1000000010002, 0x2, 0x0)
	/usr/local/go/src/net/tcpsock.go:248 +0x47
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc0004318c0, 0xc00004daa0, 0xc0000c9140, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:82 +0x6e
created by github.com/osrg/gobgp/server.NewTCPListener
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:80 +0x274

goroutine 48 [syscall]:
syscall.Syscall6(0x120, 0x6, 0xc00050fb08, 0xc00050faec, 0x80800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.accept4(0x6, 0xc00050fb08, 0xc00050faec, 0x80800, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1484 +0x7b
syscall.Accept4(0x6, 0x80800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:541 +0x88
internal/poll.accept(0x6, 0x72, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/sock_cloexec.go:17 +0x3f
internal/poll.(*FD).Accept(0xc0003a1c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:377 +0x113
net.(*netFD).accept(0xc0003a1c80, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000431900, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000431900, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:248 +0x47
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc000431900, 0xc00004db00, 0xc0000c9140, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:82 +0x6e
created by github.com/osrg/gobgp/server.NewTCPListener
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:80 +0x274

goroutine 49 [select]:
github.com/eapache/channels.(*InfiniteChannel).infiniteBuffer(0xc000431960)
	/home/thomas/go/kube-router/vendor/github.com/eapache/channels/infinite_channel.go:49 +0x133
created by github.com/eapache/channels.NewInfiniteChannel
	/home/thomas/go/kube-router/vendor/github.com/eapache/channels/infinite_channel.go:19 +0x158

goroutine 66 [chan receive]:
github.com/osrg/gobgp/server.(*Watcher).loop(0xc0004eecc0)
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:2879 +0x7b
created by github.com/osrg/gobgp/server.(*BgpServer).Watch.func1
	/home/thomas/go/kube-router/vendor/github.com/osrg/gobgp/server/server.go:3044 +0xab9

goroutine 68 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00025e028, 0x1)
	/usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc00025e018)
	/usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc00025e000, 0xc00040e010, 0x0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:438 +0xa6
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00036e000)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000523e00)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000523e00, 0x3b9aca00, 0x0, 0xc000220f01, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc00036e000, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2fd
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc000206f30, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:220 +0x4a2
created by k8s.io/client-go/informers.(*sharedInformerFactory).Start
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/informers/factory.go:73 +0x19f

goroutine 69 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc000012568, 0x0)
	/usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc000012558)
	/usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000012540, 0xc0003d9d30, 0x0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:438 +0xa6
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0003c2000)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000071e00)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000071e00, 0x3b9aca00, 0x0, 0xc000216101, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc0003c2000, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2fd
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc000206fc0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:220 +0x4a2
created by k8s.io/client-go/informers.(*sharedInformerFactory).Start
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/informers/factory.go:73 +0x19f

goroutine 71 [chan receive]:
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc0001c22a0, 0xc00004dd40)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:418 +0x49
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000215da0, 0xc000431b40)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 72 [chan receive (nil chan)]:
k8s.io/client-go/tools/cache.(*controller).Run.func1(0x0, 0xc0003c2000)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x34
created by k8s.io/client-go/tools/cache.(*controller).Run
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0xae

goroutine 11 [chan receive]:
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc0001c2230, 0xc0000a81e0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:418 +0x49
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002c0010, 0xc0001a40a0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 12 [chan receive (nil chan)]:
k8s.io/client-go/tools/cache.(*controller).Run.func1(0x0, 0xc00036e000)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x34
created by k8s.io/client-go/tools/cache.(*controller).Run
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0xae

goroutine 73 [select]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0001cdcc0, 0x1c3ee20, 0xc0004319c0, 0xc000543be0, 0xc0002502a0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:366 +0x26e
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001cdcc0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:332 +0xe1d
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:204 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000061ef0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000543ef0, 0x3b9aca00, 0x0, 0x1, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001cdcc0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:203 +0x169
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000215e10, 0xc000431b60)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 13 [select]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc00013a0a0, 0x1c3ee20, 0xc0004319c0, 0xc000437be0, 0xc0002500c0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:366 +0x26e
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00013a0a0, 0x0, 0x0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:332 +0xe1d
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:204 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000616f0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000437ef0, 0x3b9aca00, 0x0, 0x1, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00013a0a0, 0x0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:203 +0x169
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002c00b0, 0xc0001a40c0)
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/thomas/go/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 14 [select]:
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00013a0a0, 0x0, 0xc0000a8420, 0xc0002500c0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:278 +0x178
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:272 +0x8a6

goroutine 15 [select]:
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001cdcc0, 0x0, 0xc0000a8480, 0xc0002502a0)
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:278 +0x178
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
	/home/thomas/go/kube-router/vendor/k8s.io/client-go/tools/cache/reflector.go:272 +0x8a6
FAIL	github.com/cloudnativelabs/kube-router/pkg/controllers/routing	30.039s

```

**Comment by ghouscht** [comment]
Debugging through the test showed that the deferred call to stop the bgp server here: https://github.com/cloudnativelabs/kube-router/blob/230ff155dd4f276d02c2fd9320519fe3d51a1f81/pkg/controllers/routing/network_routes_controller_test.go#L173 is blocking further execution. 

Digging deeper showed that, somewhere in the stdlib ([internal/poll/fd_unix.go](https://github.com/golang/go/blob/a7acf9af07bdc288129fa5756768b41f312d05f4/src/internal/poll/fd_unix.go#L109)) the call to close the underlying file descriptor blocks, this can also be seen in the stack trace:

```
goroutine 45 [semacquire]:
internal/poll.runtime_Semacquire(0xc0003a1b28)
	/usr/local/go/src/runtime/sema.go:61 +0x42
internal/poll.(*FD).Close(0xc0003a1b00, 0xc0003a1b00, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:109 +0x8f
```

**Comment by ghouscht** [comment]
Found [this](https://github.com/osrg/gobgp/commit/9a0323419e9481186340a6455553fbc515969258) in the release notes for gobgp v2.0.0, so the closing of the listening socket was a known problem, that came up with go 1.11. 

Unfortunately kube-router still uses gobgp v1.33 and in v2.0.0 the api of gobgp changed quite a bit. Probably it's best to upgrade gobgp to a recent version prior to switch to go modules?

**Comment by aauren** [comment]
Also resolves #636

**Comment by williamh** [comment]
Hi all, I am a packager for Gentoo linux, and I am wondering what the possibility of this happening before version 1.0 is released is?

It would make downstream packaging quite a bit easier.

Thanks much,

William

**Comment by aauren** [comment]
Thanks for your effort @ghouscht!

This work is superseded by #976 and is about to be merged into master via: #982

**Pull request closed without merging**
