### PR TITLE
Feature Route Reflector

### PR DESCRIPTION
**Pull request by ut0mt8**
Enable Route Reflector feature as discusses in issue #192 . 3rd try.

### CODE REVIEW

**Comment by murali-reddy** [comment]
@ut0mt8 thanks agin. LGTM. But will wait if any one has any comments.

cc: @roffe @andrewsykim

**Comment by murali-reddy** [comment]
Tested. Works great!!

**Comment by murali-reddy** [comment]
@ut0mt8 Any possible enhancements you can think off? Is it not RR server SPOF?

**Comment by ut0mt8** [comment]
@murali-reddy One RR server is a big spof for sure. But for real production cluster my advice is to two flag/annotate two or three node as route-server (I think the best place is on master node ?). 
This way you can have a fully redundant RR setup. And bonus it already work, I ve tested it.

**Comment by ut0mt8** [comment]
We may wrote a little explanation text or made a schema for setup such an HA RR. It is natural for me as I was an network engineer in an other life, but I may be hard to understand for people with no network background.

**Comment by murali-reddy** [comment]
>  for real production cluster my advice is to two flag/annotate two or three node as route-server 

I missed that part. Yes, redundent RR server should work. I will try it out. Thanks.

**Comment by murali-reddy** [comment]
@ut0mt8 come to think of this feature, it could not have been more elegent.

https://twitter.com/cloudnativelabs/status/969425663722635264

I have added you on Kubernetes kube-router [slack](https://kubernetes.slack.com/messages/C8DCQGTSB/details/). You dont use slack?

**Comment by ut0mt8** [comment]
Thks you. I use slack but I am not the k8s slack for the moment.

**Comment by andrewsykim** [comment]
@ut0mt8 sorta late to the party, but really glad this feature is in, will try to give it a test soon :)

**Comment by andrewsykim** [comment]
@ut0mt8 cluster ID in this case is the same as internal ASN?

**Comment by ut0mt8** [comment]
@andrewsykim nope ClusterID is read from annotation. however it seems that there is a bug on gobgp side cause whatever I set, clusterid seems always 0.0.0.0 at the end. I may open an issue on gobgp if it cause pain to someone.

**Pull request merged**
