### PR TITLE
Fix DSR(tunneling) mode mtu limit

### PR DESCRIPTION
**Pull request by icefed**
fix https://github.com/cloudnativelabs/kube-router/issues/630

### CODE REVIEW

**Comment by rearden-steel** [comment]
@murali-reddy any news on merging it??

**Comment by murali-reddy** [comment]
@rearden-steel Will take a look at the fix next week.

**Comment by rearden-steel** [comment]
@murali-reddy please check it, this issue affects our production environment.
Thank you.

**Comment by murali-reddy** [comment]
@rearden-steel Sure. I dont have first hand knowledge of solutions that can address the problem. So I had to educate a bit. Did you run the fix in prodcution successfully?

@icefed sorry for getting back on this PR embarrassingly late. From what I understand approach in this fix is similar to MSS clamping done by middleboxes. How did you come up with 1440 value for MSS?

**Comment by icefed** [comment]
@murali-reddy In the TCP/IP protocal, IP Header and TCP Header both use 20bytes, if client and server have same MTU like 1500, the MSS which is exchanged by TCP HandShake only have 1460bytes; But DSR(tunneling)ip-ip use 20bytes, the packet is biger than server MTU. 
Make client side MTU lower 20bytes than server (client 1480 and server 1500)is a solution, but we can not do that. So we can set MSS to 1440  that make 20bytes space for ip-ip tunnel.

**Comment by murali-reddy** [comment]
@icefed thanks for explanation. 

I was wondering in case of cross subnet/zone traffic we will end up traffic double encapsulated So when client access external IP on node A, it get IPIP encapsulated to say pod B running on node B. If node A and node B are in different subnet then kube-router uses IP-IP tunneling. Did you by any chance try the solution on multi subnet scenario?

**Comment by icefed** [comment]
@murali-reddy Sorry, I have no resource to test now.

**Comment by MrFreezeex** [comment]
Will this works if the IP packet has options ? Not sure if this is relevant though...

**Comment by icefed** [comment]
@murali-reddy I think 1400 is a acceptable MSS value for all network env, also need someone to test.

**Comment by qingkunl** [comment]
I've tested this change. It works for the case where kube-bridge and pod eth0 have 1500 as MTU.

However, v1.1.0 has added --auto-mtu flag (https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#mtu), which might set kube-bridge and pod MTU to a different value.

Is that possible to calculate the MSS in this change based on kube-bridge and pod MTU value, instead of hardcoding it to 1440?

Thanks

**Comment by qingkunl** [comment]
> @murali-reddy I think 1400 is a acceptable MSS value for all network env, also need someone to test.

@icefed Yeah, since the cross subnet tunnel has 1460 MTU, 1400 MSS works. We've tested in our production.

**Comment by yydzhou** [comment]
@aauren @murali-reddy is there any progress or timeline on this? This is a desired fix for me too. We have cross sbunet tunnel setup and need to set the mss to 1400.

**Comment by aauren** [comment]
@icefed Thanks for your work on this!

I cherry-picked your commit into #1063 and added additional functionality to automatically find the TCPMSS based upon interface MTU.

Closing this as it is replaced by #1063

**Pull request closed without merging**
