### PR TITLE
Change outbound nodeport rule to accept RELATED and ESTABLISHED traffic

### PR DESCRIPTION
**Pull request by RaveNoX**
This pull request fixes issue #692

### CODE REVIEW

**Comment by murali-reddy** [comment]
@RaveNoX thanks for the PR and detailed bug report #692 

I don't recall why (but very likely due docker changing default FORWRD policy as described in https://github.com/kubernetes/kubernetes/issues/39823) that rule was added as part of #120. Current rule is a bad solution. So it must be changed.

I need to test it to understand better. But here are the questions that are going through my mind

- Is ACCEPT for RELATED and ESTABLISHED  is enough? Does IPVS<-->real-server traffic is considered RELATED to the client<-->IPVS
- Does the packet hit FORWARD chain, from http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.filter_rules.html it indicates packet may go through the POSTROUTING chain

Let me try the fix and revert back

**Comment by RaveNoX** [comment]
Here a good guide about IPVS & IPTABLES interaction:
http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.filter_rules.html

**Comment by RaveNoX** [comment]
Hello!
Is there any news on this issue?

**Comment by trnl** [comment]
@RaveNoX, thanks for the fix! 

@murali-reddy  I wonder if there are any updates from your side? It looks like we are hitting the same problem at the end.

**Comment by RaveNoX** [comment]
@murali-reddy any news on this?

**Pull request closed without merging**
