### PR TITLE
use conflist format for all deploys

### PR DESCRIPTION
**Pull request by MarkDeckert**
use conflist format for all deploys

### CODE REVIEW

**Comment by MarkDeckert** [comment]
PR for https://github.com/cloudnativelabs/kube-router/issues/684

I realized while making the changes this is essentially identical to what is already done in the hostport example manifest.  I just ticked up the cni version number to 0.6.0.

**Comment by murali-reddy** [comment]
@MarkDeckert thanks for the PR. Please rebase.

Does it also make sense to remove previous file (if it exists) with `.conf` extension. I believe if there exists more than one config file, first one in lexicographic order will be chosen by kubelet when kube-router might use one with `.conflist` extension.

**Comment by MarkDeckert** [comment]
I've messed this one up massively trying to correct a few things.  I will do a new PR

**Comment by MarkDeckert** [comment]
@murali-reddy thank you for mentioning the kubelet behavior.  Current kubelet documentation proves that to be correct.  It does make sense to remove previous .conf files.  I will be doing a new PR though for other reasons.

I also considered deleting/handling any previous .conflist files as well, but that gets into a bunch of other issues so in that case might be better to just let it break.

**Pull request closed without merging**
