### PR TITLE
move to Go modules and update k8s api machinery to latest

### PR DESCRIPTION
**Pull request by murali-reddy**
remove use of dep and move to go mod

update the below vendored libaries to latest
```
k8s.io/api v0.18.6
k8s.io/apimachinery v0.18.6
k8s.io/client-go v0.18.6
```

### CODE REVIEW

**Comment by aauren** [comment]
@murali-reddy is this meant to go in after #948 ?

**Comment by murali-reddy** [comment]
Yes base branch for the PR is 1.1 as well and yes its on top of #948

**Comment by aauren** [comment]
Resolves: #419

**Review by mrueg — APPROVED** [review]

**Comment by murali-reddy** [comment]
thanks @aauren @mrueg. Merging the PR

Forgot to highlight a point. Since gobgp is at major version v2+ there are certain enforcements to be followed as per 

https://github.com/golang/go/wiki/Modules#semantic-import-versioning
https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

typically importing module should use major version in import path but gobgp does not have `github.com/osrg/gobgp/v2`

https://github.com/osrg/gobgp/issues/2274

so right now I have hardcoded to a commit (coresponding to gobgp 2.19 release) in `go.mod`

`github.com/osrg/gobgp v0.0.0-20200806055634-c6f0eba8f4d8`

**Pull request merged**
