### PR TITLE
skip binding device to ipip tunnel if node's interface is loopback

### PR DESCRIPTION
**Pull request by tamihiro**
When tunnel interface's source address is on loopback, the tunnel should not be bound  to `lo`. Otherwise, packets cannot leave from egress interface to the tunnel peer.

### CODE REVIEW

**Comment by aauren** [comment]
@murali-reddy I'd appreciate your thoughts on this one also

**Comment by aauren** [comment]
@tamihiro Sorry, that this is taking so long. Recently, the project has had other priorities.

RE: https://github.com/cloudnativelabs/kube-router/issues/778#issuecomment-817393713 I'm seeking Murali's thoughts. You can wait for that to go through, or if you're willing it would help if you would proactively rebase so this is ready whenever I hear back.

**Comment by tamihiro** [comment]
@aauren I rebased this one as well  as #777, working good on my dev cluster.

**Comment by aauren** [comment]
@tamihiro Thanks for doing all of this work. Sorry it took so long for us to finally come back around to this!

**Pull request merged**
