### PR TITLE
DockerInDocker local cluster + e2e testing + CI

### LINKED ISSUE #28: Have test framework in place for CI
Quality Assurance: Have a basic test framework in place that can find some issues/regressions without manual testing. Using and passing kubernetes conformance tests would also help alleviate fears of new software.

### PR DESCRIPTION
**Pull request by bzub**
Fixes #28

### CODE REVIEW

**Comment by murali-reddy** [comment]
@bzub Very impressive work. I understand its still in WIP. When its ready, is it possible for travis to post  back e2e test results to the PR/bug?

**Comment by murali-reddy** [comment]
Could you please rebase to master, i have fixed failing network policy e2e tests.

**Comment by bzub** [comment]
DinD fails too many e2e tests out of the box. This PR is has been replaced by #140

**Comment by murali-reddy** [comment]
Sad, DinD has technical limitations. It would have been clean approach with no external dependencies.

**Comment by bzub** [comment]
Yup. I'm keeping the branch around in case e2e can be fixed upstream.

**Pull request closed without merging**
