### PR TITLE
Routes Synchronization Routine [Fixes #509]

### LINKED ISSUE #509: Route table gone forever after network interface link down and up
I just found a weird behavior of kube-router that cause an outage in my cluster.

There was an event (not confirmed by AWS) that cause an host interface link down and then up.
After that event, all nodes inside cluster (including master node) lost a route table and it cause all pods communication to be failed.

You can easily reproduce this by provision a cluster, deploy some application and then just run `if down eth0 && if up eth0` with root account in any node.

After that, check route table `ip route` and all routes gone. To resolve that I have to manually restart kube-router and wait a couple minute to see route table come back again.

Please help.
Thanks

Environment:
Cloud: AWS
Kubernetes: 1.9.3
OS: Debian GNU/Linux 9 (stretch) 4.9.0-5-amd64
Docker: 17.3.2
Kube-router: 0.1.0

### PR DESCRIPTION
**Pull request by Rusox89**
I've separated the synchronization of routes with the host from the event watching on MonitorTable

### CODE REVIEW

**Comment by Rusox89** [comment]
Hi @aauren, could you please enable the workflow once more please?

**Comment by aauren** [comment]
> Hi @aauren, could you please enable the workflow once more please?

It looks like it's already enabled and was run 5 hours ago.

**Comment by aauren** [comment]
Thanks for submitting this @Rusox89. We're still focusing on bug fixes for the 1.3 release for a bit. This work is a bit of a larger fix in that it adds a new kube-router parameter to the mix, so we'll likely wait until we start work on 1.4 to take a look. I've added it to the 1.4 project that we use to sort features and requests for the next release.

**Comment by aauren** [comment]
@Rusox89 Sorry that it took so long to come back around to this MR!

Since its been a while I didn't want to put the owness of rebasing and incorporating feedback on you, so I cherry-picked your commit into #1262 and added a few things.

Thanks for your work on this!

**Pull request closed without merging**
