### PR TITLE
fix(network_policy): match twice KUBE-POD-FW chain during firewall sync

### PR DESCRIPTION
**Pull request by liuxu623**
We should create `default rule to REJECT traffic destined for POD` before create `rule to jump traffic destined to POD`.

### CODE REVIEW

**Comment by murali-reddy** [comment]
@liuxu623  sorry what is the problem this PR is trying to address. Its not clear

**Comment by liuxu623** [comment]
> @liuxu623 sorry what is the problem this PR is trying to address. Its not clear

During firewall sync, maybe `-A FORWARD -s 10.0.0.1/32 -m physdev --physdev-is-bridged -m comment --comment "rule to jump traffic from POD name:test namespace: default to chain KUBE-POD-FW-QM6NAHJOX6WYUFNJ" -j KUBE-POD-FW-QM6NAHJOX6WYUFNJ` rule has been inserted, but `-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -m comment --comment "default rule to REJECT traffic destined for POD name:test namespace: default" -j REJECT --reject-with icmp-port-unreachable` rule doesn't inserted.

The packet maybe match `KUBE-POD-FW-QM6NAHJOX6WYUFNJ` and `KUBE-POD-FW-R42BDHVPLAFLWKJQ` unit `-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -m comment --comment "default rule to REJECT traffic destined for POD name:test namespace: default" -j REJECT`.

```
-A FORWARD -s 10.0.0.1/32 -m physdev --physdev-is-bridged -m comment --comment "rule to jump traffic from POD name:test namespace: default to chain KUBE-POD-FW-QM6NAHJOX6WYUFNJ" -j KUBE-POD-FW-QM6NAHJOX6WYUFNJ
-A FORWARD -s 10.0.0.1/32 -m comment --comment "rule to jump traffic from POD name:test namespace: default to chain KUBE-POD-FW-QM6NAHJOX6WYUFNJ" -j KUBE-POD-FW-QM6NAHJOX6WYUFNJ

-A FORWARD -s 10.0.0.1/32 -m physdev --physdev-is-bridged -m comment --comment "rule to jump traffic from POD name:test namespace: default to chain KUBE-POD-FW-R42BDHVPLAFLWKJQ" -j KUBE-POD-FW-R42BDHVPLAFLWKJQ
-A FORWARD -s 10.0.0.1/32 -m comment --comment "rule to jump traffic from POD name:test namespace: default to chain KUBE-POD-FW-R42BDHVPLAFLWKJQ" -j KUBE-POD-FW-R42BDHVPLAFLWKJQ

-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -m comment --comment "rule for stateful firewall for pod" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -d 10.0.0.1/32 -m comment --comment "rule to permit the traffic traffic to pods when source is the pod\'s local node" -m addrtype --src-type LOCAL -j ACCEPT
-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -m comment --comment "run through nw policy test1" -j KUBE-NWPLCY-L4DVY2QQADQ2JEVM
...
-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -m comment --comment "run through nw policy test10" -j KUBE-NWPLCY-XYMTOCYG3JXNKKWU
~~-A KUBE-POD-FW-QM6NAHJOX6WYUFNJ -m comment --comment "default rule to REJECT traffic destined for POD name:test namespace: default" -j REJECT --reject-with icmp-port-unreachable~~

-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -m comment --comment "rule for stateful firewall for pod" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -d 10.0.0.1/32 -m comment --comment "rule to permit the traffic traffic to pods when source is the pod\'s local node" -m addrtype --src-type LOCAL -j ACCEPT
-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -m comment --comment "run through nw policy test1" -j KUBE-NWPLCY-5DBWSULJNJHHYLCX
...
-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -m comment --comment "run through nw policy test10" -j KUBE-NWPLCY-ZEDBN75MK5HYZ25T
-A KUBE-POD-FW-R42BDHVPLAFLWKJQ -m comment --comment "default rule to REJECT traffic destined for POD name:test namespace: default" -j REJECT
```

**Comment by liuxu623** [comment]
@murali-reddy This PR could improve performance and make logic more clear, we should create all KUBE-POD-FW rules before create FORWARD rules, and also can avoid problem like #807.

**Comment by aauren** [comment]
Closing this PR as this work was accomplished during: #915

**Pull request closed without merging**
